/**
 * E2E demo — OpenAIRealtimeAgentAdapter as the user simulator
 * (`role=AgentRole.USER`). Binds the `@e2e @ts-openai-realtime-user-demo`
 * scenario from `specs/voice-agents.feature`.
 *
 * Critical proof for §7.2: scripted `user("text")` lines route through
 * `sendText`, NOT through TTS. The realtime model converts the text into
 * spoken audio with natural prosody on the server side.
 *
 * Env-gated on `OPENAI_API_KEY`.
 */

import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { loadFeature, describeFeature } from "@amiceli/vitest-cucumber";
import { AgentRole, voice } from "@langwatch/scenario";
import { expect } from "vitest";

const { AudioChunk, OPENAI_REALTIME_MODEL, OpenAIRealtimeAgentAdapter } = voice;

const HERE = dirname(fileURLToPath(import.meta.url));
const FEATURE_PATH = resolve(
  HERE,
  "..",
  "..",
  "..",
  "..",
  "..",
  "specs",
  "voice-agents.feature",
);

const RUN_E2E = Boolean(process.env.OPENAI_API_KEY);

const feature = await loadFeature(FEATURE_PATH);

describeFeature(
  feature,
  ({ Scenario }) => {
    const Bind = RUN_E2E ? Scenario : Scenario.skip;

    Bind(
      "Demo — OpenAI Realtime as the user simulator",
      ({ Given, When, Then, And }) => {
        let adapter: voice.OpenAIRealtimeAgentAdapter;
        let firstChunk: voice.AudioChunk;

        Given(
          "an OpenAIRealtimeAgentAdapter with role=AgentRole.USER and a confused-elderly-customer persona",
          () => {
            adapter = new OpenAIRealtimeAgentAdapter({
              model: OPENAI_REALTIME_MODEL,
              voice: "nova",
              instructions:
                "You are a confused elderly customer trying to reset your password. " +
                "Speak slowly with hesitation.",
              role: AgentRole.USER,
            });
            expect(adapter.role).toBe(AgentRole.USER);
          },
        );

        When("the demo script runs via scenario.run()", async () => {
          await adapter.connect();
          // sendText is the user-role path: scripted text goes straight
          // into the realtime session as an input_text content part.
          await adapter.sendText("I forgot my password and need help.");
          firstChunk = await adapter.receiveAudio(20);
        });

        Then(
          'scripted user("text") lines are delivered with natural prosody',
          () => {
            expect(firstChunk).toBeInstanceOf(AudioChunk);
            expect(firstChunk.data.length).toBeGreaterThan(0);
            // Audio came back from the live model — the user simulator
            // produced spoken audio for the scripted line.
          },
        );

        And("text TTS is bypassed for the user simulator", async () => {
          // No TTS module is imported by this demo and `sendText` is the
          // only path used to inject the scripted line. The live audio
          // returned in `When` is generated by the realtime model itself.
          await adapter.disconnect();
        });
      },
    );
  },
  { includeTags: ["ts-openai-realtime-user-demo"] },
);
