"""Abstract base class for red-team attack strategies."""

from abc import ABC, abstractmethod


class RedTeamStrategy(ABC):
    """Abstract base for all red-team attack strategies."""

    @abstractmethod
    def build_system_prompt(
        self,
        target: str,
        current_turn: int,
        total_turns: int,
        scenario_description: str,
        metaprompt_plan: str = "",
        **kwargs,
    ) -> str:
        """Return the system prompt for this turn.

        Args:
            target: The attack objective.
            current_turn: Current turn number (1-indexed).
            total_turns: Total turns in the conversation.
            scenario_description: Description of the scenario/agent under test.
            metaprompt_plan: The attack plan generated by the metaprompt model.
            **kwargs: Additional strategy-specific parameters.
        """
        ...
