packages:
  - .
  - examples/*
  - examples/openai-realtime-demo
  - examples/openai-realtime-demo/realtime-client
  - examples/vitest/tests/realtime/realtime-client

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - "@swc/core"
  - sharp
