[project]
name = "agno-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.6.4",
    "create-agent-app",
    "langwatch>=0.2.4",
    "langwatch-scenario>=0.7.1",
    "openinference-instrumentation-agno>=0.1.6",
    "pytest>=8.3.5",
    "python-dotenv>=1.1.0",
]

[tool.uv.sources]
create-agent-app = { path = "../../../../examples/create_agent_app", editable = true }
