/**
 * tee-substrate — capture the subject's RAW `stream-json` stdout as the PRIMARY
 * judged substrate, and read it back as normalized turns.
 *
 * Why tee stdout (not the on-disk flat JSONL): on claude 2.1.207 a FRESH
 * `claude -p` session can write only an eager `ai-title` STUB to its on-disk
 * session file (the real records go elsewhere), so grading that file grades an
 * empty transcript. The `--output-format stream-json --verbose` STDOUT
 * definitely carries intact `tool_use`/`tool_result` (it is how the adapter
 * builds its response). We tee THAT to `<workDir>/.transcript/<n>.stream.jsonl`.
 *
 * No core edits: capture happens at the `claudeBin` spawn layer via a shell shim
 * that pipes the real CLI's stdout through `tee`. Point the adapter at the shim
 * with `claudeBin` / `CLAUDE_BIN`, and set `ADHERENCE_TRANSCRIPT_DIR` in its env.
 *
 * Parsing reuses the exported {@link parseStreamJson} — the exact same parser the
 * adapter uses — so the judge reads structurally identical messages.
 */

import { readFileSync, readdirSync, writeFileSync, chmodSync, mkdirSync } from "node:fs";
import { join } from "node:path";

import { parseStreamJson, type ClaudeStreamMessage } from "@langwatch/scenario";
import type { NormalizedTurn } from "./types.ts";
import { normalizeTurns } from "./normalize.ts";

export const TRANSCRIPT_SUBDIR = ".transcript";

/**
 * Bash source for the `claudeBin` tee shim. It runs the REAL claude with all
 * args, pipes stdout through `tee` into a per-invocation file under
 * `$ADHERENCE_TRANSCRIPT_DIR`, records the prompt (last arg) in a sidecar, and
 * preserves the CLI's own exit code. `realClaude` is baked in so the shim never
 * re-invokes itself (which would loop).
 */
export function teeShimSource(realClaude: string): string {
  return `#!/usr/bin/env bash
# Auto-generated by tee-substrate.ts. Tees claude stdout to the transcript dir.
set -o pipefail
dir="\${ADHERENCE_TRANSCRIPT_DIR:?ADHERENCE_TRANSCRIPT_DIR must be set}"
mkdir -p "$dir"
# Monotonic per-invocation index (one claude -p spawn == one scenario turn).
idx_file="$dir/.counter"
n=$(( $(cat "$idx_file" 2>/dev/null || echo 0) + 1 ))
echo "$n" > "$idx_file"
# Record the prompt (last positional arg) so readSubstrate can synthesize the
# human turn even if the CLI does not echo it as a user event.
prompt="\${!#}"
printf '%s' "$prompt" > "$dir/$n.prompt.txt"
# Optional subject-model override for the model-sweep: inject --model when
# ADHERENCE_SUBJECT_MODEL is set; empty/unset ⇒ account default (current behavior,
# byte-identical). Placed before "$@" (the adapter passes no --model, so this is
# the only one → it wins).
model_args=()
if [ -n "\${ADHERENCE_SUBJECT_MODEL:-}" ]; then model_args=(--model "\${ADHERENCE_SUBJECT_MODEL}"); fi
${JSON.stringify(realClaude)} "\${model_args[@]}" "$@" | tee "$dir/$n.stream.jsonl"
exit "\${PIPESTATUS[0]}"
`;
}

/** Write + chmod the tee shim. Returns the shim path. */
export function writeTeeShim(shimPath: string, realClaude: string): string {
  writeFileSync(shimPath, teeShimSource(realClaude), "utf8");
  chmodSync(shimPath, 0o755);
  return shimPath;
}

/** Ensure the transcript dir exists (called by the harness before a run). */
export function ensureTranscriptDir(workDir: string): string {
  const dir = join(workDir, TRANSCRIPT_SUBDIR);
  mkdirSync(dir, { recursive: true });
  return dir;
}

function numericTurnIndex(file: string): number {
  const m = /^(\d+)\.stream\.jsonl$/.exec(file);
  return m ? Number(m[1]) : Number.MAX_SAFE_INTEGER;
}

/**
 * Read every `<n>.stream.jsonl` under `<workDir>/.transcript`, in turn order, as
 * RAW {@link ClaudeStreamMessage}[]. Each turn's human prompt (from the
 * `<n>.prompt.txt` sidecar) is injected as a synthetic `user` event ahead of
 * that turn's events, so a real human turn is always present in the substrate.
 */
export function readRawSubstrate(workDir: string): ClaudeStreamMessage[] {
  const dir = join(workDir, TRANSCRIPT_SUBDIR);
  let files: string[];
  try {
    files = readdirSync(dir).filter((f) => f.endsWith(".stream.jsonl"));
  } catch {
    return [];
  }
  files.sort((a, b) => numericTurnIndex(a) - numericTurnIndex(b));

  const all: ClaudeStreamMessage[] = [];
  for (const file of files) {
    const n = numericTurnIndex(file);
    // Synthesize the human prompt turn from the sidecar, if present.
    try {
      const prompt = readFileSync(join(dir, `${n}.prompt.txt`), "utf8");
      if (prompt.trim()) {
        all.push({
          type: "user",
          message: { role: "user", content: prompt },
        });
      }
    } catch {
      /* no sidecar — the CLI's own user event (if any) will carry it */
    }
    const stdout = readFileSync(join(dir, file), "utf8");
    const { messages } = parseStreamJson(stdout);
    all.push(...messages);
  }
  return all;
}

/** Read the tee'd substrate as normalized turns — the judge's input. */
export function readSubstrate(workDir: string): NormalizedTurn[] {
  return normalizeTurns(readRawSubstrate(workDir));
}
